bot:
  name: TelegaCategoriesBot
  token: 6753913476:AAFqF9UGozmkmfd1diuniExEc_9HnmAZdWg
  chatId:
spring:
  jpa:
    database: PostgreSQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://java-postgres:5432/postgres
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    locations: classpath:db/migration
    default-schema: flyway_schema


